random-xs:
  faiss_IVFPQ:
    docker-tag: neurips23-congestion-faiss_IVFPQ
    module: neurips23.congestion.faiss_IVFPQ.faiss_IVFPQ
    constructor: faiss_IVFPQ
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "IVF1024,SQ8"}]
        query-args: |
            [{"nprobe": 1}, {"nprobe": 4}, {"nprobe": 16}, {"nprobe": 64}]
msturing-10M-clustered:
  faiss_IVFPQ:
    docker-tag: neurips23-congestion-faiss_IVFPQ
    module: neurips23.congestion.faiss_IVFPQ.faiss_IVFPQ
    constructor: faiss_IVFPQ
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "IVF1024,SQ8"}]
        query-args: |
          [{"nprobe": 1}, {"nprobe": 4}, {"nprobe": 16}, {"nprobe": 64}]