random-xs:
  ipdiskann:
    docker-tag: neurips23-congestion-ipdiskann
    module: neurips23.congestion.ipdiskann.ipdiskann
    constructor: IPdiskann
    base-args: [ "@metric" ]
    run-groups:
      base:
        args: |
          [{
            "R": 64,
            "L": 80,
            "num_threads": 1,
            "insert_thread_count": 8,
            "search_thread_count": 8
            },
            {
            "R": 64,
            "L": 100,
            "num_threads": 1,
            "insert_thread_count": 8,
            "search_thread_count": 8
            },
            {
            "R": 32,
            "L": 100,
            "num_threads": 1,
            "insert_thread_count": 8,
            "search_thread_count": 8
            },
            {
            "R": 32,
            "L": 80,
            "num_threads": 1,
            "insert_thread_count": 8,
            "search_thread_count": 8
            }
          ]
        query-args: |
          [
            {
            "L": 128,
            "K": 10
            }
          ]