random-xs:
  faiss_lsh:
    docker-tag: neurips23-congestion-faiss_lsh
    module: neurips23.congestion.faiss_lsh.faiss_lsh
    constructor: faiss_lsh
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "LSH"}]
        query-args: |
            [{"ef":30}]
msturing-10M-clustered:
  faiss_lsh:
    docker-tag: neurips23-congestion-faiss_lsh
    module: neurips23.congestion.faiss_lsh.faiss_lsh
    constructor: faiss_lsh
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "LSH"}]
        query-args: |
          [{"ef":30}]
