random-xs:
  FreshDiskANN:
    docker-tag: neurips23-congestion-FreshDiskANN
    module: neurips23.congestion.FreshDiskANN.FreshDiskANN
    constructor: FreshDiskANN
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"R": 32, "L": 100, "num_threads": 32, "insert_thread_count": 32, "search_thread_count": 32}]
        query-args: |
            [{"L": 100}]
msturing-10M-clustered:
  FreshDiskANN:
    docker-tag: neurips23-congestion-FreshDiskANN
    module: neurips23.congestion.FreshDiskANN.FreshDiskANN
    constructor: FreshDiskANN
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"R": 32, "L": 100, "num_threads": 32, "insert_thread_count": 32, "search_thread_count": 32}]
        query-args: |
            [{"L": 100}]