random-xs:
  FreshDiskANN:
    docker-tag: neurips23-congestion-FreshDiskANN
    module: neurips23.congestion.FreshDiskANN.FreshDiskANN
    constructor: FreshDiskANN
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"R": 10, "L": 20, "num_threads": 8, "insert_thread_count": 4, "search_thread_count": 4}]
        query-args: |
            [{"L": 20}]
msturing-10M-clustered:
  FreshDiskANN:
    docker-tag: neurips23-congestion-FreshDiskANN
    module: neurips23.congestion.FreshDiskANN.FreshDiskANN
    constructor: FreshDiskANN
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"R": 64, "L": 100, "num_threads": 8, "insert_thread_count": 4, "search_thread_count": 4}]
        query-args: |
            [{"L": 20}]