random-xs:
  candy_sptag:
    docker-tag: neurips23-congestion-candy_sptag
    module: neurips23.congestion.candy_sptag.candy_sptag
    constructor: candy_sptag
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "SPTAG"}]
        query-args: |
          [{"ef":30}]
msturing-10M-clustered:
  candy_sptag:
    docker-tag: neurips23-congestion-candy_sptag
    module: neurips23.congestion.candy_sptag.candy_sptag
    constructor: candy_sptag
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "SPTAG"}]
        query-args: |
          [
          {"ef":90},
          ]
