random-xs:
  faiss_fast_scan:
    docker-tag: neurips23-congestion-faiss_fast_scan
    module: neurips23.congestion.faiss_fast_scan.faiss_fast_scan
    constructor: faiss_fast_scan
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "IVF2000,PQ4x4fs,RFlat"}]
        query-args: |
          [ {"ef":100}]
#msturing-10M-clustered:
#  faiss_fast_scan:
#    docker-tag: neurips23-congestion-faiss_fast_scan
#    module: neurips23.congestion.faiss_fast_scan.faiss_fast_scan
#    constructor: faiss_fast_scan
#    base-args: ["@metric"]
#    run-groups:
#      base:
#        args: |
#          [{"indexkey": "IVF2000,PQ50x4fs,RFlat"}]
#        query-args: |
#          [
#          {"ef":100}
#          ]
