random-xs:
  faiss_fast_scan:
    docker-tag: neurips23-streaming-faiss_fast_scan
    module: neurips23.streaming.faiss_fast_scan.faiss_fast_scan
    constructor: faiss_fast_scan
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "IVF2000,PQ10x4fs,RFlat"}]
        query-args: |
          [{"ef":30}, {"ef":50}, {"ef":100}]
msturing-10M-clustered:
  faiss_fast_scan:
    docker-tag: neurips23-streaming-faiss_fast_scan
    module: neurips23.streaming.faiss_fast_scan.faiss_fast_scan
    constructor: faiss_fast_scan
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "IVF2000,PQ50x4fs,RFlat"}]
        query-args: |
          [
          {"ef":90},
          {"ef":95},
          {"ef":100},
          {"ef":102},
          {"ef":104},
          {"ef":106},
          {"ef":108},
          {"ef":110},
          {"ef":115},
          {"ef":120}
          ]
