random-xs:
  faiss_hnsw_incremental:
    module: benchmark_anns.bench.algorithms.faiss_hnsw_incremental.faiss_hnsw_incremental
    constructor: FaissHnswIncremental
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"efConstruction": 120, "indexkey": "HNSWIncremental16"}]
        query-args: |
          [{"ef": 40}]

sift:
  faiss_hnsw_incremental:
    module: benchmark_anns.bench.algorithms.faiss_hnsw_incremental.faiss_hnsw_incremental
    constructor: FaissHnswIncremental
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"efConstruction": 120, "indexkey": "HNSWIncremental16","verbose": true}]
        query-args: |
          [{"ef": 120, "warm_start_levels": 2, "direct_reuse": false}]
