random-xs:
  gti:
    docker-tag: neurips23-congestion-gti
    module: neurips23.congestion.gti.gti
    constructor: GTI_Index
    base-args: [ "@metric" ]
    run-groups:
      base:
        args: |
          [
            {"capacity_up_i": 64, "capacity_up_l": 2, "m": 16},
            {"capacity_up_i": 64, "capacity_up_l": 4, "m": 16},
            {"capacity_up_i": 128, "capacity_up_l": 2, "m": 16},
            {"capacity_up_i": 128, "capacity_up_l": 4, "m": 16}
          ]
        query-args: |
          [
            {"L": 60,"K": 10}
          ]