random-xs:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]
random-xs-clustered:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]
msspacev-1M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]
msturing-1M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]
wikipedia-1M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":100, "insert_threads":32, "consolidate_threads":32}]
          query-args: |
            [
             {"Ls":100, "T":32}]
wikipedia-35M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":100, "insert_threads":32, "consolidate_threads":32}]
          query-args: |
            [
             {"Ls":100, "T":32}]
msspacev-10M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-10M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-10M-clustered:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-30M-clustered:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16},
             {"R":32, "L":70, "insert_threads":16, "consolidate_threads":16},
             {"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":70, "T":16}]

sift-small:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

glove:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

sift:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

msong:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

sun:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

dpr:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

reddit:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

coco:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

trevi:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

wte-0.05:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

wte-0.1:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

wte-0.2:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

wte-0.4:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

wte-0.6:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

openimage-streaming:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

wte-0.8:
    diskann:
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]



random-plus:
  diskann:
    docker-tag: neurips23-streaming-diskann
    module: neurips23.streaming.diskann.diskann-str
    constructor: diskann
    base-args: [ "@metric" ]
    run-groups:
      base:
        args: |
          [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
        query-args: |
          [{"Ls":50, "T":8}]
