random-xs:
  faiss_NSW:
    docker-tag: neurips23-congestion-faiss_NSW
    module: neurips23.congestion.faiss_NSW.faiss_NSW
    constructor: faiss_NSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "NSW32"}]
        query-args: |
          [{"ef":30}]
msturing-10M-clustered:
  faiss_NSW:
    docker-tag: neurips23-congestion-faiss_NSW
    module: neurips23.congestion.faiss_NSW.faiss_NSW
    constructor: faiss_NSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "NSW32"}]
        query-args: |
          [
          {"ef":100}
          ]
